export const APPLICATION_FORM_FIELDS = [
  {
    id: 'fullname',
    name: 'fullname',
    label: 'Họ và tên',
    type: 'text',
  },
  {
    id: 'birthday',
    name: 'birthday',
    label: 'Ngày sinh',
    type: 'date',
    format: 'DD/MM/YYYY',
  },
  {
    id: 'gender',
    name: 'gender',
    label: 'Giới tính',
    type: 'select',
    options: [
      { value: 'Nam', label: 'Nam' },
      { value: 'Nữ', label: 'Nữ' },
      { value: 'Khác', label: 'Khác' },
    ],
  },
  {
    id: 'email',
    name: 'email',
    label: 'Email',
    type: 'text',
  },
  {
    id: 'phone',
    name: 'phone',
    label: 'Số điện thoại',
    type: 'text',
  },
  {
    id: 'family',
    name: 'family',
    label: 'Gia đình',
    type: 'text',
    multiline: true,
  },
  {
    id: 'healthStatus',
    name: 'healthStatus',
    label: 'Tình trạng sức khỏe',
    type: 'text',
    multiline: true,
  },
  {
    id: 'hometown',
    name: 'hometown',
    label: 'Quê quán',
    type: 'text',
  },
  {
    id: 'university',
    name: 'university',
    label: 'Trường Đại học',
    type: 'text',
  },
  {
    id: 'major',
    name: 'major',
    label: 'Ngành học',
    type: 'text',
  },
  {
    id: 'careerGoal',
    name: 'careerGoal',
    label: 'Mục tiêu nghề nghiệp',
    type: 'text',
  },
  {
    id: 'scholarEssay',
    name: 'scholarEssay',
    label: 'Tại sao bạn muốn nhận học bổng này?',
    type: 'text',
    multiline: true,
    minRows: 5,
  },
];
