'use client';
import { ThemeProvider, createTheme } from '@mui/material';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { LocalizationProvider } from '@mui/x-date-pickers';
import { AdapterMoment } from '@mui/x-date-pickers/AdapterMoment';

const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

const theme = createTheme({});

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <ThemeProvider theme={theme}>
      <LocalizationProvider dateAdapter={AdapterMoment}>
        <html lang="en">
          <body className={inter.className}>{children}</body>
        </html>
      </LocalizationProvider>
    </ThemeProvider>
  );
}
