'use client';
import { ThemeProvider, createTheme } from '@mui/material';
import './globals.css';
import { Inter } from 'next/font/google';
import { LocalizationProvider } from '@mui/x-date-pickers';
import { AdapterMoment } from '@mui/x-date-pickers/AdapterMoment';

const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

declare module '@mui/material/styles' {
  // add h0 to the typography variant for typescript
  interface TypographyVariants {
    h0: React.CSSProperties;
  }
  // allow configuration using `createTheme`
  interface TypographyVariantsOptions {
    h0?: React.CSSProperties;
  }
}

declare module '@mui/material/Typography' {
  interface TypographyPropsVariantOverrides {
    h0: true;
  }
}

const theme = createTheme({
  typography: {
    h0: {
      fontSize: '3rem',
      fontWeight: 'bold',
    },
    h1: {
      fontSize: '2rem',
      fontWeight: 'bold',
    },
  },
});

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <ThemeProvider theme={theme}>
      <LocalizationProvider dateAdapter={AdapterMoment}>
        <html lang="en">
          <body className={inter.className}>{children}</body>
        </html>
      </LocalizationProvider>
    </ThemeProvider>
  );
}
